import type {
  NarrationGameConfidenceV1,
  NarrationGameFeatureV1,
  NarrationGameSourceAuthorityV1,
  NarrationGameSystemV1,
} from "./narration-game-catalog";

const ACCESSED_ON = "2026-07-30";

type PopularGameDefinition = Readonly<{
  id: string;
  displayName: string;
  aliases: readonly string[];
  feature: NarrationGameFeatureV1;
  minimumOccurrences: number;
  evidenceStrength: NarrationGameConfidenceV1;
  confidenceCeiling: NarrationGameConfidenceV1;
  claim: string;
  confusableWith: readonly string[];
  commentaryTopics: readonly string[];
  authority: NarrationGameSourceAuthorityV1;
  publisher: string;
  sourceTitle: string;
  sourceUrl: `https://${string}`;
}>;

const DEFINITIONS = [
  {
    id: "pathfinder-1e",
    displayName: "Pathfinder First Edition",
    aliases: ["pathfinder first edition", "pathfinder 1e", "pf1e", "pf1"],
    feature: "single-d20-plus-modifier",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "weak",
    claim: "Pathfinder First Edition uses modified d20 checks.",
    confusableWith: ["dungeons-and-dragons-3-5e", "dungeons-and-dragons-5e-2014"],
    commentaryTopics: ["d20-checks", "pathfinder-first-edition"],
    authority: "licensed-rules-reference",
    publisher: "Paizo",
    sourceTitle: "Pathfinder Reference Document: Getting Started",
    sourceUrl: "https://legacy.aonprd.com/coreRuleBook/gettingStarted.html",
  },
  {
    id: "world-of-darkness-5e-family",
    displayName: "World of Darkness 5th Edition family",
    aliases: [
      "world of darkness",
      "vampire the masquerade",
      "vampire v5",
      "vtm v5",
      "werewolf the apocalypse",
      "werewolf v5",
      "hunter the reckoning",
      "hunter v5",
    ],
    feature: "plain-d10-pool",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "plausible",
    claim: "World of Darkness fifth-edition games use pools of ten-sided dice.",
    confusableWith: ["shadowrun-6e-family", "other-d10-pool-games"],
    commentaryTopics: ["d10-pool", "hunger-and-desperation-dice"],
    authority: "publisher",
    publisher: "Renegade Game Studios",
    sourceTitle: "Vampire: The Masquerade 5th Edition Core Rulebook",
    sourceUrl: "https://renegadegamestudios.com/pdf-vampire-the-masquerade/",
  },
  {
    id: "cyberpunk-red",
    displayName: "Cyberpunk RED",
    aliases: ["cyberpunk red", "cyberpunk edgerunners", "cp red", "cpr"],
    feature: "single-d10-plus-modifier",
    minimumOccurrences: 2,
    evidenceStrength: "plausible",
    confidenceCeiling: "plausible",
    claim: "Cyberpunk RED resolves checks with a modified d10 roll.",
    confusableWith: ["other-single-d10-games"],
    commentaryTopics: ["d10-checks", "critical-rolls"],
    authority: "publisher",
    publisher: "R. Talsorian Games",
    sourceTitle: "Cyberpunk RED Core Book FAQ: Skill Checks",
    sourceUrl: "https://rtalsoriangames.com/wp-content/uploads/2021/07/RTG-CPR-CoreBookFAQv1.3.pdf",
  },
  {
    id: "pokemon-tabletop-united",
    displayName: "Pokémon Tabletop United",
    aliases: ["pokemon tabletop united", "pokémon tabletop united", "ptu"],
    feature: "plain-d6-pool",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "plausible",
    claim: "Pokémon Tabletop United commonly combines d6 skill pools with d20 accuracy rolls.",
    confusableWith: ["other-d6-pool-games", "d20-family-games"],
    commentaryTopics: ["d6-skills", "d20-accuracy"],
    authority: "official-srd",
    publisher: "Pokémon Tabletop United creators",
    sourceTitle: "Pokémon Tabletop United 1.05 downloads and resources",
    sourceUrl: "https://pokemontabletop.com/downloads-and-resources/",
  },
  {
    id: "lancer",
    displayName: "Lancer",
    aliases: ["lancer", "lancer rpg", "lancer ttrpg"],
    feature: "d20-with-accuracy-d6",
    minimumOccurrences: 1,
    evidenceStrength: "strong",
    confidenceCeiling: "strong",
    claim: "Lancer applies accuracy or difficulty by keeping the highest d6 alongside a d20 check.",
    confusableWith: ["other-d20-plus-d6-games"],
    commentaryTopics: ["accuracy-dice", "difficulty-dice"],
    authority: "publisher",
    publisher: "Massif Press",
    sourceTitle: "Lancer Core Book: free player-facing PDF",
    sourceUrl: "https://massif-press.itch.io/corebook-pdf-free",
  },
  {
    id: "powered-by-the-apocalypse-family",
    displayName: "Powered by the Apocalypse family",
    aliases: [
      "powered by the apocalypse",
      "pbta",
      "monster of the week",
      "masks a new generation",
      "avatar legends",
      "monsterhearts",
      "urban shadows",
      "thirsty sword lesbians",
    ],
    feature: "two-d6-plus-modifier",
    minimumOccurrences: 2,
    evidenceStrength: "plausible",
    confidenceCeiling: "plausible",
    claim: "Many Powered by the Apocalypse games resolve moves with 2d6 plus a stat.",
    confusableWith: ["traveller-mongoose-2e", "other-two-d6-games"],
    commentaryTopics: ["two-d6-moves", "move-outcomes"],
    authority: "publisher",
    publisher: "Lumpley Games",
    sourceTitle: "What is PbtA?",
    sourceUrl: "https://lumpley.games/2023/11/22/what-is-pbta/",
  },
  {
    id: "genesys-star-wars-family",
    displayName: "Genesys and Star Wars Narrative Dice family",
    aliases: [
      "genesys",
      "star wars rpg",
      "star wars ffg",
      "edge of the empire",
      "age of rebellion",
      "force and destiny",
    ],
    feature: "mixed-step-dice-pool",
    minimumOccurrences: 1,
    evidenceStrength: "plausible",
    confidenceCeiling: "strong",
    claim: "Genesys and the related Star Wars games use mixed narrative-dice pools.",
    confusableWith: ["fabula-ultima", "other-mixed-dice-pool-games"],
    commentaryTopics: ["narrative-dice", "mixed-dice-pools"],
    authority: "publisher",
    publisher: "Edge Studio",
    sourceTitle: "Genesys Core Rulebook",
    sourceUrl: "https://www.edge-studio.net/games/genesys-core-rulebook/",
  },
  {
    id: "two-d20-family",
    displayName: "2d20 System family",
    aliases: [
      "2d20",
      "fallout 2d20",
      "star trek adventures",
      "dune adventures in the imperium",
      "conan 2d20",
    ],
    feature: "two-d20-roll-under-threshold",
    minimumOccurrences: 1,
    evidenceStrength: "strong",
    confidenceCeiling: "strong",
    claim: "The 2d20 System rolls two d20s against a target number and counts successes.",
    confusableWith: ["other-multiple-d20-games"],
    commentaryTopics: ["two-d20", "success-counting"],
    authority: "official-srd",
    publisher: "Modiphius Entertainment",
    sourceTitle: "2d20 World Builders and System Reference Document",
    sourceUrl: "https://modiphius.net/pages/2d20worldbuilders",
  },
  {
    id: "starfinder",
    displayName: "Starfinder",
    aliases: ["starfinder", "starfinder 1e", "starfinder 2e", "sf1e", "sf2e"],
    feature: "single-d20-plus-modifier",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "weak",
    claim: "Starfinder uses modified d20 checks.",
    confusableWith: ["pathfinder-1e", "pathfinder-2e-remaster", "d20-family-games"],
    commentaryTopics: ["d20-checks", "science-fantasy"],
    authority: "publisher",
    publisher: "Paizo",
    sourceTitle: "Starfinder Roleplaying Game",
    sourceUrl: "https://paizo.com/starfinder",
  },
  {
    id: "fabula-ultima",
    displayName: "Fabula Ultima",
    aliases: ["fabula ultima", "fabula ultima ttrpg"],
    feature: "mixed-step-dice-pool",
    minimumOccurrences: 2,
    evidenceStrength: "plausible",
    confidenceCeiling: "plausible",
    claim: "Fabula Ultima checks combine two attribute dice that can have different step sizes.",
    confusableWith: ["genesys-star-wars-family", "other-step-die-games"],
    commentaryTopics: ["attribute-dice", "high-roll-pairs"],
    authority: "publisher",
    publisher: "Need Games",
    sourceTitle: "Fabula Ultima Press Kit",
    sourceUrl: "https://www.needgames.it/fabula-ultima-en/#presskit",
  },
  {
    id: "shadowrun-6e-family",
    displayName: "Shadowrun Sixth World family",
    aliases: ["shadowrun", "shadowrun sixth world", "shadowrun 6e", "sr6"],
    feature: "plain-d6-pool",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "plausible",
    claim: "Shadowrun Sixth World resolves tests with pools of six-sided dice.",
    confusableWith: ["year-zero-engine-family", "other-d6-pool-games"],
    commentaryTopics: ["d6-pool", "hits"],
    authority: "publisher",
    publisher: "Catalyst Game Labs",
    sourceTitle: "Shadowrun Sixth World Beginner Box",
    sourceUrl: "https://store.catalystgamelabs.com/products/shadowrun-sixth-world-beginner-box-1",
  },
  {
    id: "warhammer-fantasy-roleplay-4e",
    displayName: "Warhammer Fantasy Roleplay Fourth Edition",
    aliases: ["warhammer fantasy roleplay", "warhammer fantasy 4e", "wfrp", "wfrp 4e"],
    feature: "percentile-roll-under-threshold",
    minimumOccurrences: 2,
    evidenceStrength: "plausible",
    confidenceCeiling: "plausible",
    claim: "Warhammer Fantasy Roleplay Fourth Edition uses a d100 system.",
    confusableWith: ["basic-roleplaying-2023", "call-of-cthulhu-7e", "delta-green"],
    commentaryTopics: ["percentile-checks", "degrees-of-success"],
    authority: "publisher",
    publisher: "Cubicle 7",
    sourceTitle: "Cubicle 7 d100 game system catalogue",
    sourceUrl: "https://cubicle7games.com/en_US/game-systems/d100",
  },
  {
    id: "shadowdark",
    displayName: "Shadowdark RPG",
    aliases: ["shadowdark", "shadowdark rpg"],
    feature: "single-d20-plus-modifier",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "weak",
    claim: "Shadowdark is a d20-based, roll-high game.",
    confusableWith: ["old-school-essentials", "dungeons-and-dragons-5e-2014"],
    commentaryTopics: ["d20-checks", "old-school-play"],
    authority: "publisher",
    publisher: "The Arcane Library",
    sourceTitle: "Shadowdark RPG",
    sourceUrl: "https://www.thearcanelibrary.com/products/shadowdark-rpg",
  },
  {
    id: "gurps-4e",
    displayName: "GURPS Fourth Edition",
    aliases: ["gurps", "gurps 4e", "gurps fourth edition"],
    feature: "three-d6",
    minimumOccurrences: 2,
    evidenceStrength: "plausible",
    confidenceCeiling: "plausible",
    claim: "GURPS resolves success rolls with 3d6.",
    confusableWith: ["marvel-multiverse-role-playing-game", "other-three-d6-games"],
    commentaryTopics: ["three-d6", "roll-under"],
    authority: "publisher",
    publisher: "Steve Jackson Games",
    sourceTitle: "GURPS details and GURPS Lite",
    sourceUrl: "https://www.sjgames.com/gurps/details.html",
  },
  {
    id: "year-zero-engine-family",
    displayName: "Year Zero Engine family",
    aliases: [
      "year zero engine",
      "mutant year zero",
      "alien rpg",
      "vaesen",
      "forbidden lands",
      "blade runner rpg",
      "the walking dead universe rpg",
      "coriolis",
    ],
    feature: "plain-d6-pool",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "plausible",
    claim: "The dice-pool version of the Year Zero Engine uses pools of six-sided dice.",
    confusableWith: ["shadowrun-6e-family", "other-d6-pool-games"],
    commentaryTopics: ["d6-pool", "pushing-rolls"],
    authority: "official-srd",
    publisher: "Free League Publishing",
    sourceTitle: "Year Zero Engine Standard Reference Document",
    sourceUrl: "https://freeleaguepublishing.com/wp-content/uploads/2023/11/YZE-Standard-Reference-Document.pdf",
  },
  {
    id: "cypher-system-family",
    displayName: "Cypher System family",
    aliases: ["cypher system", "numenera", "the strange", "old gods of appalachia rpg"],
    feature: "single-d20-roll",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "plausible",
    claim: "Cypher System task resolution uses a player-facing d20 roll against a target number.",
    confusableWith: ["d20-family-games"],
    commentaryTopics: ["d20-tasks", "difficulty-levels"],
    authority: "publisher",
    publisher: "Monte Cook Games",
    sourceTitle: "Do Not Let the Dice Fall Where They May",
    sourceUrl: "https://www.montecookgames.com/do-not-let-the-dice-fall-where-they-may/",
  },
  {
    id: "delta-green",
    displayName: "Delta Green",
    aliases: ["delta green", "delta green rpg"],
    feature: "percentile-roll-under-threshold",
    minimumOccurrences: 2,
    evidenceStrength: "plausible",
    confidenceCeiling: "plausible",
    claim: "Delta Green uses percentile skill tests.",
    confusableWith: ["call-of-cthulhu-7e", "basic-roleplaying-2023", "warhammer-fantasy-roleplay-4e"],
    commentaryTopics: ["percentile-checks", "critical-percentiles"],
    authority: "publisher",
    publisher: "Arc Dream Publishing",
    sourceTitle: "Delta Green Publications: Need to Know quickstart rules",
    sourceUrl: "https://www.delta-green.com/publications/",
  },
  {
    id: "traveller-mongoose-2e",
    displayName: "Traveller (Mongoose Second Edition)",
    aliases: ["traveller", "mongoose traveller", "traveller 2e", "mgt2"],
    feature: "two-d6-plus-modifier",
    minimumOccurrences: 2,
    evidenceStrength: "plausible",
    confidenceCeiling: "plausible",
    claim: "Mongoose Traveller resolves skill checks with 2d6 plus modifiers.",
    confusableWith: ["powered-by-the-apocalypse-family", "other-two-d6-games"],
    commentaryTopics: ["two-d6-checks", "effect"],
    authority: "publisher",
    publisher: "Mongoose Publishing",
    sourceTitle: "Traveller Explorer's Edition",
    sourceUrl: "https://www.mongoosepublishing.com/products/traveller-explorers-edition",
  },
  {
    id: "dragonbane",
    displayName: "Dragonbane",
    aliases: ["dragonbane", "drakar och demoner"],
    feature: "d20-roll-under-threshold",
    minimumOccurrences: 2,
    evidenceStrength: "plausible",
    confidenceCeiling: "strong",
    claim: "Dragonbane uses skill-based d20 roll-under checks.",
    confusableWith: ["other-d20-roll-under-games"],
    commentaryTopics: ["d20-roll-under", "boons-and-banes"],
    authority: "publisher",
    publisher: "Free League Publishing",
    sourceTitle: "Dragonbane",
    sourceUrl: "https://freeleaguepublishing.com/games/dragonbane/",
  },
  {
    id: "daggerheart",
    displayName: "Daggerheart",
    aliases: ["daggerheart", "daggerheart rpg"],
    feature: "two-d12-plus-modifier",
    minimumOccurrences: 2,
    evidenceStrength: "strong",
    confidenceCeiling: "strong",
    claim: "Daggerheart action rolls use two d12 Duality Dice plus modifiers.",
    confusableWith: ["other-two-d12-games"],
    commentaryTopics: ["duality-dice", "hope-and-fear"],
    authority: "official-srd",
    publisher: "Darrington Press",
    sourceTitle: "Daggerheart System Reference Document",
    sourceUrl: "https://www.daggerheart.com/wp-content/uploads/2025/05/DH-SRD-May202025.pdf",
  },
  {
    id: "cosmere-roleplaying-game",
    displayName: "Cosmere Roleplaying Game",
    aliases: ["cosmere roleplaying game", "cosmere rpg", "stormlight rpg"],
    feature: "d20-with-plot-d6",
    minimumOccurrences: 1,
    evidenceStrength: "strong",
    confidenceCeiling: "strong",
    claim: "The Cosmere Roleplaying Game can add a d6 Plot Die to a d20 test.",
    confusableWith: ["lancer", "other-d20-plus-d6-games"],
    commentaryTopics: ["plot-die", "d20-tests"],
    authority: "official-srd",
    publisher: "Brotherwise Games",
    sourceTitle: "Cosmere Roleplaying Game Downloads",
    sourceUrl: "https://www.cosmererpg.com/downloads",
  },
  {
    id: "draw-steel",
    displayName: "Draw Steel",
    aliases: ["draw steel", "draw steel rpg"],
    feature: "two-d10-plus-modifier",
    minimumOccurrences: 2,
    evidenceStrength: "plausible",
    confidenceCeiling: "strong",
    claim: "Draw Steel uses 2d10 power rolls with tiered outcomes.",
    confusableWith: ["other-two-d10-games"],
    commentaryTopics: ["two-d10", "tiered-outcomes"],
    authority: "publisher",
    publisher: "MCDM Productions",
    sourceTitle: "Draw Steel Rules Reference",
    sourceUrl: "https://files.mcdmproductions.com/DrawSteel/DrawSteelRulesReferenceV1.pdf",
  },
  {
    id: "dungeon-crawl-classics",
    displayName: "Dungeon Crawl Classics RPG",
    aliases: ["dungeon crawl classics", "dcc rpg", "dcc"],
    feature: "dcc-dice-chain",
    minimumOccurrences: 1,
    evidenceStrength: "distinctive",
    confidenceCeiling: "distinctive",
    claim: "Dungeon Crawl Classics uses a distinctive dice chain including d3, d5, d7, d14, d16, d24, and d30.",
    confusableWith: ["other-unusual-dice-games"],
    commentaryTopics: ["dice-chain", "zocchi-dice"],
    authority: "publisher",
    publisher: "Goodman Games",
    sourceTitle: "Dungeon Crawl Classics Quick Start Rules",
    sourceUrl: "https://goodman-games.com/wp-content/uploads/2020/03/DCC_QSR_Free.pdf",
  },
  {
    id: "marvel-multiverse-role-playing-game",
    displayName: "Marvel Multiverse Role-Playing Game",
    aliases: ["marvel multiverse role playing game", "marvel multiverse rpg", "marvel d616", "d616"],
    feature: "three-d6",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "plausible",
    claim: "The Marvel Multiverse d616 System rolls three six-sided dice.",
    confusableWith: ["gurps-4e", "other-three-d6-games"],
    commentaryTopics: ["three-d6", "marvel-die"],
    authority: "publisher",
    publisher: "Marvel",
    sourceTitle: "Marvel Multiverse Role-Playing Game developer update",
    sourceUrl: "https://www.marvel.com/articles/culture-lifestyle/marvel-multiverse-role-playing-game-developer-update-2-powers-combat-faq",
  },
  {
    id: "old-school-essentials",
    displayName: "Old-School Essentials",
    aliases: ["old school essentials", "ose", "old school essentials advanced fantasy"],
    feature: "single-d20-plus-modifier",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "weak",
    claim: "Old-School Essentials supports d20 attack rolls with attack bonuses.",
    confusableWith: ["shadowdark", "dungeons-and-dragons-3-5e"],
    commentaryTopics: ["d20-attacks", "old-school-play"],
    authority: "official-srd",
    publisher: "Necrotic Gnome",
    sourceTitle: "Old-School Essentials SRD: Combat Tables",
    sourceUrl: "https://oldschoolessentials.necroticgnome.com/srd/index.php/Combat_Tables",
  },
  {
    id: "warhammer-40000-wrath-and-glory",
    displayName: "Warhammer 40,000 Roleplay: Wrath & Glory",
    aliases: ["wrath and glory", "wrath & glory", "warhammer 40k wrath and glory", "w&g"],
    feature: "plain-d6-pool",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "plausible",
    claim: "Wrath & Glory uses a d6 dice-pool system.",
    confusableWith: ["year-zero-engine-family", "shadowrun-6e-family"],
    commentaryTopics: ["d6-pool", "wrath-die"],
    authority: "publisher",
    publisher: "Cubicle 7",
    sourceTitle: "Warhammer 40,000 Roleplay: Wrath & Glory",
    sourceUrl: "https://cubicle7games.com/our-games/wrath-glory",
  },
  {
    id: "the-dark-eye-5e",
    displayName: "The Dark Eye Fifth Edition",
    aliases: ["the dark eye", "the dark eye 5e", "das schwarze auge", "dsa5", "tde5"],
    feature: "three-d20",
    minimumOccurrences: 1,
    evidenceStrength: "strong",
    confidenceCeiling: "strong",
    claim: "The Dark Eye Fifth Edition uses three-d20 attribute checks.",
    confusableWith: ["other-multiple-d20-games"],
    commentaryTopics: ["three-d20", "attribute-checks"],
    authority: "publisher",
    publisher: "Ulisses Spiele",
    sourceTitle: "The Dark Eye Quick-Start Rules",
    sourceUrl: "https://ulisses-spiele.de/wp-content/uploads/2025/06/The_Dark_Eye_Quickstart_rules.pdf",
  },
  {
    id: "tormenta20",
    displayName: "Tormenta20",
    aliases: ["tormenta20", "tormenta 20", "t20 rpg"],
    feature: "single-d20-plus-modifier",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "weak",
    claim: "Tormenta20 uses d20 checks.",
    confusableWith: ["d20-family-games"],
    commentaryTopics: ["d20-checks", "tormenta"],
    authority: "licensed-rules-reference",
    publisher: "Jambô Editora and Roll20",
    sourceTitle: "Tormenta20 Introductory Kit",
    sourceUrl: "https://marketplace.roll20.net/browse/module/19562/tormenta20-introductory-kit",
  },
  {
    id: "world-of-darkness-20th-anniversary-family",
    displayName: "World of Darkness 20th Anniversary family",
    aliases: [
      "world of darkness 20th anniversary",
      "classic world of darkness",
      "vampire 20th anniversary",
      "vampire v20",
      "v20",
      "mage 20th anniversary",
      "mage m20",
      "werewolf 20th anniversary",
      "werewolf w20",
      "chronicles of darkness",
    ],
    feature: "plain-d10-pool",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "plausible",
    claim: "Classic World of Darkness games use d10 dice pools.",
    confusableWith: ["world-of-darkness-5e-family", "other-d10-pool-games"],
    commentaryTopics: ["d10-pool", "success-counting"],
    authority: "publisher",
    publisher: "Onyx Path Publishing",
    sourceTitle: "Onyx Path games and d10 dice pools",
    sourceUrl: "https://theonyxpath.com/just-a-roll-of-the-dice-monday-meeting-notes/",
  },
  {
    id: "level-up-advanced-5e",
    displayName: "Level Up: Advanced 5th Edition",
    aliases: ["level up advanced 5th edition", "level up a5e", "advanced 5e", "a5e"],
    feature: "single-d20-plus-modifier",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "weak",
    claim: "Level Up Advanced 5th Edition uses modified d20 checks.",
    confusableWith: ["dungeons-and-dragons-5e-2014", "dungeons-and-dragons-5e-2024"],
    commentaryTopics: ["d20-checks", "advanced-fifth-edition"],
    authority: "official-srd",
    publisher: "EN Publishing",
    sourceTitle: "Advanced 5E System Reference Document",
    sourceUrl: "https://a5esrd.com/",
  },
  {
    id: "warhammer-40000-imperium-maledictum",
    displayName: "Warhammer 40,000 Roleplay: Imperium Maledictum",
    aliases: ["imperium maledictum", "warhammer 40k imperium maledictum", "wh40k im"],
    feature: "percentile-roll-under-threshold",
    minimumOccurrences: 2,
    evidenceStrength: "plausible",
    confidenceCeiling: "plausible",
    claim: "Imperium Maledictum uses a d100 system.",
    confusableWith: ["warhammer-fantasy-roleplay-4e", "other-percentile-games"],
    commentaryTopics: ["percentile-checks", "degrees-of-success"],
    authority: "publisher",
    publisher: "Cubicle 7",
    sourceTitle: "Warhammer 40,000 Roleplay: Imperium Maledictum",
    sourceUrl: "https://cubicle7games.com/our-games/warhammer-40k-roleplay-imperium-maledictum",
  },
  {
    id: "star-wars-5e",
    displayName: "Star Wars 5e",
    aliases: ["star wars 5e", "sw5e", "star wars fifth edition"],
    feature: "single-d20-plus-modifier",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "weak",
    claim: "Star Wars 5e uses the fifth-edition d20 rules framework.",
    confusableWith: ["dungeons-and-dragons-5e-2014", "genesys-star-wars-family"],
    commentaryTopics: ["d20-checks", "star-wars"],
    authority: "official-srd",
    publisher: "Star Wars 5e creators",
    sourceTitle: "Star Wars 5e Player's Handbook",
    sourceUrl: "https://sw5e.com/rules/phb",
  },
  {
    id: "dungeons-and-dragons-5e-2024",
    displayName: "Dungeons & Dragons 5e (2024)",
    aliases: [
      "dungeons and dragons 2024",
      "d&d 2024",
      "dnd 2024",
      "d&d 5e 2024",
      "dnd 5.5e",
      "5.5e",
    ],
    feature: "single-d20-plus-modifier",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "weak",
    claim: "Dungeons & Dragons 2024 uses modified d20 tests.",
    confusableWith: ["dungeons-and-dragons-5e-2014", "d20-family-games"],
    commentaryTopics: ["d20-checks", "fifth-edition-2024"],
    authority: "publisher",
    publisher: "Wizards of the Coast",
    sourceTitle: "D&D 2024 Basic Rules: Playing the Game",
    sourceUrl: "https://www.dndbeyond.com/sources/dnd/br-2024/playing-the-game",
  },
  {
    id: "candela-obscura",
    displayName: "Candela Obscura",
    aliases: ["candela obscura", "illuminated worlds", "illuminated worlds system"],
    feature: "d6-pool-keep-highest",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "plausible",
    claim: "Candela Obscura uses the d6-pool Illuminated Worlds System.",
    confusableWith: ["forged-in-the-dark-family", "other-d6-pool-games"],
    commentaryTopics: ["d6-pool", "gilded-die"],
    authority: "publisher",
    publisher: "Darrington Press",
    sourceTitle: "Candela Obscura Quickstart Guide",
    sourceUrl: "https://darringtonpress.com/play-candela-obscura-with-our-new-quickstart-guide/",
  },
  {
    id: "dungeons-and-dragons-3-5e",
    displayName: "Dungeons & Dragons 3.5e",
    aliases: ["dungeons and dragons 3.5", "d&d 3.5", "dnd 3.5", "dnd 3.5e", "3.5e"],
    feature: "single-d20-plus-modifier",
    minimumOccurrences: 2,
    evidenceStrength: "weak",
    confidenceCeiling: "weak",
    claim: "Dungeons & Dragons 3.5e uses modified d20 checks.",
    confusableWith: ["pathfinder-1e", "dungeons-and-dragons-5e-2014"],
    commentaryTopics: ["d20-checks", "third-edition"],
    authority: "licensed-rules-reference",
    publisher: "Wizards of the Coast SRD",
    sourceTitle: "Revised d20 System Reference Document",
    sourceUrl: "https://www.d20srd.org/index.htm",
  },
] as const satisfies readonly PopularGameDefinition[];

function toSystem(definition: PopularGameDefinition): NarrationGameSystemV1 {
  const sourceId = `${definition.id}-rules`;
  const claim = definition.claim
    .toLowerCase()
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-|-$/gu, "");
  return {
    id: definition.id,
    displayName: definition.displayName,
    aliases: definition.aliases,
    legacyRetrievalExcluded: true,
    fingerprints: [
      {
        id: `${definition.id}-mechanic`,
        claim,
        features: [definition.feature],
        minimumOccurrences: definition.minimumOccurrences,
        evidenceStrength: definition.evidenceStrength,
        confidenceCeiling: definition.confidenceCeiling,
        sourceIds: [sourceId],
        commentaryTopics: definition.commentaryTopics,
      },
    ],
    confusableWith: definition.confusableWith,
    commentaryTopics: definition.commentaryTopics,
    sources: [
      {
        id: sourceId,
        authority: definition.authority,
        publisher: definition.publisher,
        title: definition.sourceTitle,
        url: definition.sourceUrl,
        accessedOn: ACCESSED_ON,
      },
    ],
  };
}

export const NARRATION_POPULAR_GAME_SYSTEMS_V1 = DEFINITIONS.map(toSystem);
